### PR TITLE
Portfolio three by two

### PR DESCRIPTION
**Pull request by MangeFre**
[Ticket](https://trello.com/c/JxTsiLjf)

This PR includes some "proxy" posts that are not meant to be in the master branch. They are simply there for displaying how the layout will work once we add real posts.

The images that are displayed in the portfolio view also need styling, but I'd like to hear Joseph's input on how they should behave.

### CODE REVIEW

**Comment by MangeFre** [comment]
[Preview](https://deploy-preview-108--thirsty-davinci-2a9aa9.netlify.app/portfolio)

**Comment by jrapala** [comment]
Just wondering if this is ready for review? It's in a Draft state. 

Thanks!

**Comment by MangeFre** [comment]
Oh, this can be reviewed as is! The draft part mostly came from the proxy posts.

**Comment by jrapala** [comment]
@MangeFre Nice job :) Joseph added a "3x2" section to Figma. Does this answer your behavior questions? Just wondering if we can style this up before we merge.

Thanks!

**Review by jrapala — APPROVED** [review]

**Pull request merged**
