### PR TITLE
Make cards responsive

### PR DESCRIPTION
**Pull request by daleinen7**
[Ticket](https://trello.com/c/7QVcRNUP/55-adjust-2-cards-styles-to-match-new-responsive-designs)

### CODE REVIEW

**Comment by laurencun** [comment]
It's looking like the space between p.cardText and the link below it is at 18px, but according to Figma should be at 24px. 
On mobile, I'm seeing 10px of extra padding on the top of the h4.cardTitle section and 15px of extra padding on the sides of the cards. Could you take another look? Let me know if you need clarification.

**Comment by daleinen7** [comment]
> It's looking like the space between p.cardText and the link below it is at 18px, but according to Figma should be at 24px.
> On mobile, I'm seeing 10px of extra padding on the top of the h4.cardTitle section and 15px of extra padding on the sides of the cards. Could you take another look? Let me know if you need clarification.

Thanks for catching those. Got them fixed.

**Comment by laurencun** [comment]
Nice, I see you got rid of the extra padding on the sides of the cards. It's looking like there's a little too much space between the card text and link now. Could you take it from 32px to 24px?
Screen Shot 2021-02-24 at 5 20 40 PM

**Comment by daleinen7** [comment]
Weird ... SASS wasn't letting me style the descendent paragraphs of cardText. I just use regular CSS and it seems like it's working now. Thanks for catching that for me.

**Review by laurencun — APPROVED** [review]
Looks good to me! Let's move this card to test in Trello.

**Review by jrapala — CHANGES_REQUESTED** [review]
Nice job! Noticed one thing..

At 424px at under, the `H4` font sizes become bigger than they should be. Not seeing this happen on production. Can you take a look?

PR:

Screen Shot 2021-02-25 at 2 47 54 PM

Design:

Screen Shot 2021-02-25 at 2 47 35 PM

**Comment by daleinen7** [comment]
I tracked it to the _type.scss adding ```!important``` to h2 tags at that breakpoint. I just added !important to the .cardContainer class. Is that the best way to handle that? I'm not really familiar with Bootstrap and why it would have that. Let me know what you think @jrapala

**Comment by jrapala** [comment]
> I tracked it to the _type.scss adding `!important` to h2 tags at that breakpoint. I just added !important to the .cardContainer class. Is that the best way to handle that? I'm not really familiar with Bootstrap and why it would have that. Let me know what you think @jrapala

Yeah, that's fine. We need to override the Bootstrap styles here.
Maybe in the future, we can completely remove Bootstrap from this project 🤞

**Review by jrapala — CHANGES_REQUESTED** [review]
Still seeing issues with the `H4`s in mobile. (From [this](https://github.com/Code-For-Chicago/code-for-chicago-jekyll/pull/96#pullrequestreview-599022858) comment). Can you adjust?

**Comment by daleinen7** [comment]
Oops. I was so excited I found out why it was doing it, I forgot to fix the h4 as well. Thanks!

**Review by jrapala — APPROVED** [review]

**Pull request merged**
