### PR TITLE
Work with us styles responsive designs

### PR DESCRIPTION
**Pull request by daleinen7**
[Ticket](https://trello.com/c/Bf9IWNYa/50-adjust-work-with-us-styles-to-match-new-responsive-designs)

### CODE REVIEW

**Comment by jrapala** [comment]
i'm going to hold off on reviewing this until https://trello.com/c/2XXLfvum is merged in (updated Work with Us icons)

**Comment by jrapala** [comment]
Looks like that icon update got merged in. Can you please merge in Master and I'll give it a review?

Thanks!

**Comment by laurencun** [comment]
It looks like there’s an additional 24px of space between the work with us header and the icons section on mobile. Could you take a look there?

**Comment by daleinen7** [comment]
Thanks for the catch!

**Review by jrapala — CHANGES_REQUESTED** [review]
The vertical spacing between the icons needs a slight adjust.

In the two-column mode, I'm seeing 60px between the icons (two margins of 30px).
This 60px gap exists in the one-column mode as well.

PR:

Screen Shot 2021-02-25 at 3 47 38 PM


Design:

Screen Shot 2021-02-25 at 3 51 44 PM
Screen Shot 2021-02-25 at 3 51 30 PM

**Review by jrapala — CHANGES_REQUESTED** [review]
Can you please also revisit the spacing above and below the header & paragraph?. Seems to be larger than it needs to be.

PR:

Screen Shot 2021-02-25 at 3 56 25 PM


Design:

Screen Shot 2021-02-25 at 3 56 45 PM

**Comment by daleinen7** [comment]
Wild, I didn't even catch that copy change! I just alternated their display to none depending on the screen size. Does that make sense?

**Review by jrapala — CHANGES_REQUESTED** [review]
One last thing I just noticed and then this should be good to go :)

The `U` in `Work with Us` should be capitalized:

PR:

Screen Shot 2021-03-02 at 4 29 02 PM

Design:

Screen Shot 2021-03-02 at 4 29 17 PM

**Review by jrapala — APPROVED** [review]

**Pull request merged**
