### PR TITLE
Case study page

### PR DESCRIPTION
**Pull request by MangeFre**
For anyone reviewing, just checkout the branch like normal and start the server like you always do.

Then go to localhost:4000/portfolio and choose one of the posts. The one that says "Use this for testing" has some images and such to give you an idea of how it would look.

These proxy posts should be deleted before we merge this in, but I'll keep them until everything has been looked over.

### CODE REVIEW

**Comment by MangeFre** [comment]
Also - This took 1 million commits, so if we do merge it, I'll squash it

**Review by daleinen7 — CHANGES_REQUESTED** [review]
It's looking really good. Which ticket is this for though? I'm not sure if this falls into it, but it looks like the contact form isn't matching the one on the landing page. Maybe it would make sense to make the contact form into an include file? 

Also I'd like to keep all the pages in the "pages" folder. But disregard if portfolio.html isn't part of the ticket. 

It also looks like the icon in the footer breaks on the post pages, but maybe that should be its own separate ticket. I'm sure it's a Jekyll thing. 

Otherwise it looks good to me. But this is a big PR so I'm interested to see what Juliette has to say.

**Comment by MangeFre** [comment]
@daleinen7 Thanks for awesome feedback!

I forgot to link ticket, its here: https://trello.com/c/HgClaDzs
Although, I went overboard and did the case-studies part as well, my bad.

I'll move the page into the pages folder for sure, I agree that makes way more sense.

The contact form should probably be an "includes", especially if we use it in more places than one, but I'll leave as is for this PR since it is already bigger than it should be. We can make a separate ticket for that.

Final note: The share bar is not complete, it is only a placeholder. I could finish that up, but again, this PR is already bigger than it should be so it's probably better to make that a separate ticket as well.

**Review by daleinen7 — APPROVED** [review]
This looks good to me.

**Pull request merged**
