### PR TITLE
More case studies

### PR DESCRIPTION
**Pull request by daleinen7**
[ticket](https://trello.com/c/lcd1ZuQg/89-case-studies-match-previews-at-bottom-to-figma-design)

### CODE REVIEW

**Review by jrapala — CHANGES_REQUESTED** [review]
This isn't quite matching the designs. Is this a work in progress?

PR:

Screen Shot 2021-04-26 at 6 28 14 PM

Design:

Screen Shot 2021-04-26 at 6 27 28 PM

**Comment by daleinen7** [comment]
Okay, the case-studies.html now matches what the user would see on the case study posts (in '_layouts/post.html). Here's an example post of what @MangeFre is working on I believe. 

http://localhost:4000/front-end%20+%20design/2019/09/09/Proxy-post-test-copy-2.html

But http://localhost:4000/case-studies.html should match that now (I still want to go through and delete all the pages that aren't relevant like this one). 

Let me know what you think. Thanks!

**Comment by MangeFre** [comment]
I must have misunderstood my ticket as including this part, because I already did this on my branch. Would it be ok if I just merged my branch in once it is done? It already has all the CSS of the design.

**Comment by daleinen7** [comment]
@MangeFre Yeah, I thought about asking if I could see where you were at first before starting this ticket. I should have followed my gut.

**Comment by MangeFre** [comment]
I had a similar thought, so it's my bad as well. Would you be ok holding off on this until I'm done with my branch? I'll make sure to add you on the PR for that.

**Comment by daleinen7** [comment]
No problem at all.

**Comment by daleinen7** [comment]
Closing this as it looks like most of these changes are in [This PR](https://github.com/Code-For-Chicago/code-for-chicago-jekyll/pull/131)

**Pull request closed without merging**
